version: "3.9"

services:
  back_fastapi:
    build:
    # use the current directory as the build context  
      context: ./app
      args:
        - DEV=true
    #command: uvicorn app.demo:app --host 0.0.0.0 --port 8040 --reload
    ports:
      - 8040:8040
    volumes:
      - ./app:/code
      #- dev-static-data:/vol/web
    
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme

    depends_on:
      - redis
    

  redis:
    image: redis:latest
    

  web:
    build:
      context: ./api-routes-app
    volumes:
      - ./api-routes-app:/app
    command: npm run dev
    ports:
      - "3080:3000"
    environment:
      NODE_ENV: development

